import time
import pythoncom
import win32com.client
import webbrowser
import urllib.parse


def create_issue_email_draft(issue_data: dict) -> None:
    """
    Creates a draft email in Outlook with the issue details pre-filled.
    Raises Exception if Outlook cannot be accessed.
    """
    # COM must be initialized if running in a separate thread (Flet callbacks often are)
    pythoncom.CoInitialize()

    outlook = None
    last_error = None

    # Retry loop: sometimes connecting to COM takes a moment or fails spuriously
    for attempt in range(3):
        try:
            try:
                # Try to connect to an existing Outlook instance
                outlook = win32com.client.GetActiveObject("Outlook.Application")
            except Exception:
                # Fallback: create a new instance
                try:
                    outlook = win32com.client.Dispatch("Outlook.Application")
                except Exception:
                    # Last resort: dynamic dispatch (slower but sometimes more compatible)
                    outlook = win32com.client.dynamic.Dispatch("Outlook.Application")

            if outlook:
                # Verify we can actually use the object
                try:
                    mail = outlook.CreateItem(0)  # 0 = olMailItem
                    break  # Success!
                except Exception as create_err:
                    # Connected but failed to create item; maybe stale object
                    last_error = create_err
                    outlook = None  # Force retry

        except Exception as e:
            last_error = e
            outlook = None
            time.sleep(0.5)

    if not outlook:
        # COM connection failed completely. Try mailto fallback.
        try:
            _open_mailto_fallback(issue_data)
            return
        except Exception as fallback_err:
            raise Exception(
                f"Could not connect to Outlook (COM error: {last_error}) and failed fallback ({fallback_err})"
            )

    # If we are here, 'mail' is already created in the loop, but scope might be an issue if not defined outside
    # Let's assume 'mail' variable from the successful loop iteration is available,
    # BUT in Python variables leak scope, so 'mail' is available if 'break' happened.
    # However, to be safe and clear:

    if "mail" not in locals():
        # Should have been created in the loop if outlook is set
        try:
            mail = outlook.CreateItem(0)
        except Exception as e:
            # If we are here, we connected but cannot create item.
            # We will let the outer exception handler catch this and trigger fallback.
            raise Exception(f"Failed to create mail item: {e}")

    subject = f"[Issue #{issue_data['id']}] {issue_data['title']}"

    # Construct the email body
    body = f"""
Issue #{issue_data["id"]}: {issue_data["title"]}
--------------------------------------------------
Status: {issue_data["status"]}
Assignee: {issue_data["assignee"] or "Unassigned"}
Created By: {issue_data["created_by"]}
Milestone ID: {issue_data["milestone_id"] or "None"}

Description:
{issue_data["body"]}

--------------------------------------------------
This email was generated by the Issuer App.
"""
    mail.Subject = subject
    mail.Body = body

    # Display the email window
    # False = non-modal, so it doesn't block the UI
    try:
        mail.Display(False)
    except Exception as e:
        # COM failed completely. Try mailto fallback.
        try:
            _open_mailto_fallback(issue_data)
        except Exception as fallback_err:
            raise Exception(
                f"Failed to open Outlook (COM error: {e}) and failed fallback ({fallback_err})"
            )


def _open_mailto_fallback(issue_data: dict):
    """
    Fallback using mailto: protocol when COM is broken.
    Note: mailto has length limits, so we might need to truncate.
    """
    subject = f"[Issue #{issue_data['id']}] {issue_data['title']}"
    body = f"""
Issue #{issue_data["id"]}: {issue_data["title"]}
Status: {issue_data["status"]}
Assignee: {issue_data["assignee"] or "Unassigned"}

{issue_data["body"][:500]} ... (truncated)

--------------------------------------------------
Generated by Issuer App.
"""
    params = {"subject": subject, "body": body}
    qs = urllib.parse.urlencode(params, quote_via=urllib.parse.quote)
    webbrowser.open(f"mailto:?{qs}")
